/*
 * Floorp OS Local HTTP Server API
 *
 * Floorp OS Local HTTP Server provides a minimal subset of os-apis to other local applications via HTTP/JSON. - Loopback-only server (127.0.0.1) - Optional bearer token authentication (disabled by default) - Exposes browser information, web scraping, and tab management capabilities
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateTabInstanceRequest {
    /// URL to open in new tab
    #[serde(rename = "url")]
    pub url: String,
    /// Whether to create tab in background
    #[serde(rename = "inBackground", skip_serializing_if = "Option::is_none")]
    pub in_background: Option<bool>,
}

impl CreateTabInstanceRequest {
    pub fn new(url: String) -> CreateTabInstanceRequest {
        CreateTabInstanceRequest {
            url,
            in_background: None,
        }
    }
}
