/*
 * Floorp OS Local HTTP Server API
 *
 * Floorp OS Local HTTP Server provides a minimal subset of os-apis to other local applications via HTTP/JSON. - Loopback-only server (127.0.0.1) - Optional bearer token authentication (disabled by default) - Exposes browser information, web scraping, and tab management capabilities
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Download {
    /// Download identifier
    #[serde(rename = "id")]
    pub id: i32,
    /// Download URL
    #[serde(rename = "url")]
    pub url: String,
    /// Downloaded filename
    #[serde(rename = "filename")]
    pub filename: String,
    /// Download status
    #[serde(rename = "status")]
    pub status: String,
    /// Download start timestamp (epoch milliseconds as string)
    #[serde(rename = "startTime")]
    pub start_time: String,
}

impl Download {
    pub fn new(
        id: i32,
        url: String,
        filename: String,
        status: String,
        start_time: String,
    ) -> Download {
        Download {
            id,
            url,
            filename,
            status,
            start_time,
        }
    }
}
