/*
 * Floorp OS Local HTTP Server API
 *
 * Floorp OS Local HTTP Server provides a minimal subset of os-apis to other local applications via HTTP/JSON. - Loopback-only server (127.0.0.1) - Optional bearer token authentication (disabled by default) - Exposes browser information, web scraping, and tab management capabilities
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HistoryItem {
    /// Visited URL
    #[serde(rename = "url")]
    pub url: String,
    /// Page title
    #[serde(rename = "title")]
    pub title: String,
    /// Last visit timestamp (epoch milliseconds as string)
    #[serde(rename = "lastVisitDate")]
    pub last_visit_date: String,
    /// Number of visits
    #[serde(rename = "visitCount")]
    pub visit_count: i32,
}

impl HistoryItem {
    pub fn new(
        url: String,
        title: String,
        last_visit_date: String,
        visit_count: i32,
    ) -> HistoryItem {
        HistoryItem {
            url,
            title,
            last_visit_date,
            visit_count,
        }
    }
}
