/*
 * Floorp OS Local HTTP Server API
 *
 * Floorp OS Local HTTP Server provides a minimal subset of os-apis to other local applications via HTTP/JSON. - Loopback-only server (127.0.0.1) - Optional bearer token authentication (disabled by default) - Exposes browser information, web scraping, and tab management capabilities
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Tab {
    /// Tab identifier
    #[serde(rename = "id")]
    pub id: i32,
    /// Tab URL
    #[serde(rename = "url")]
    pub url: String,
    /// Tab title
    #[serde(rename = "title")]
    pub title: String,
    /// Whether the tab is currently active
    #[serde(rename = "isActive")]
    pub is_active: bool,
    /// Whether the tab is pinned
    #[serde(rename = "isPinned")]
    pub is_pinned: bool,
}

impl Tab {
    pub fn new(id: i32, url: String, title: String, is_active: bool, is_pinned: bool) -> Tab {
        Tab {
            id,
            url,
            title,
            is_active,
            is_pinned,
        }
    }
}
