/*
 * Floorp OS Local HTTP Server API
 *
 * Floorp OS Local HTTP Server provides a minimal subset of os-apis to other local applications via HTTP/JSON. - Loopback-only server (127.0.0.1) - Optional bearer token authentication (disabled by default) - Exposes browser information, web scraping, and tab management capabilities
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TabEntry {
    /// Browser identifier
    #[serde(rename = "browserId")]
    pub browser_id: String,
    /// Tab title
    #[serde(rename = "title")]
    pub title: String,
    /// Tab URL
    #[serde(rename = "url")]
    pub url: String,
    /// Whether the tab is selected
    #[serde(rename = "selected")]
    pub selected: bool,
    /// Whether the tab is pinned
    #[serde(rename = "pinned")]
    pub pinned: bool,
}

impl TabEntry {
    pub fn new(
        browser_id: String,
        title: String,
        url: String,
        selected: bool,
        pinned: bool,
    ) -> TabEntry {
        TabEntry {
            browser_id,
            title,
            url,
            selected,
            pinned,
        }
    }
}
